-- AlterTable
ALTER TABLE "videos" ADD COLUMN     "currentTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "muted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "playbackRate" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
